### ISSUE TITLE
Cannot read property 'baseURI' of undefined

### ISSUE THREAD

**Issue by merlinnot** [PolymerElements/app-storage#105]
### Description
Resolving `BASE_URI` in `app-indexeddb-mirror/common-worker.js` does not work in certain configurations. When webcomponents-loader.js does not load HTMLImports polyfill [this](https://github.com/PolymerElements/app-storage/blob/2.0-preview/app-indexeddb-mirror/common-worker.html#L28) condition is falsy indicating we're daling with Polymer 1.

### Expected outcome

We should fix this condition.

### Actual outcome

Reading property `baseURI` of undefined `document._currentSript` throws an error.

### Steps to reproduce

1. Put an `app-indexeddb-mirror` element in the page using Polymer 2 and web components loader.
2. Open the page in Chrome 58.
3. Observe errors in console.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by timcsy** [comment]
I have the same problem, too. (My browser is Chrome, and using Polymer 2)
`Uncaught ReferenceError: HTMLImports is not defined
    at common-worker.html:28
    at common-worker.html:121
(anonymous) @ common-worker.html:28
(anonymous) @ common-worker.html:121`

**Comment by jdaroesti** [comment]
I believe the changes in the commit `fix currentScript baseURI` `2ed5fb2ec31b74b2c29fbc0312e784372880c041` from march 8 caused the problem. I tested pointing my bower_components to `b48e93147f4de60e3be09a49d9c63cff5e51e1cb` (the commit before the afore mentioned changes) and the functionality returned on Chrome.

**Comment by e111077** [comment]
Fixed in 9c5dfb3
