### ISSUE TITLE
catalog issues

### ISSUE THREAD

**Issue by blasten** [PolymerElements/app-storage#35]
When testing the catalog, I found that:
* [x] this dependency: https://github.com/PolymerElements/app-storage/blob/master/bower.json#L15 is conflicting with firebase-element.

* [x] bower.json is missing the `description` and `main` entries.
* [ ] the behaviors need the annotation `@polymerBehavior` and `@demo`

**Comment by rictic** [comment]
The first is handled by https://github.com/firebase/polymerfire/pull/1

**Comment by cdata** [comment]
Unfortunately, there is no demo for the main app-storage repo yet.
