### ISSUE TITLE
README generated by tedium doesn't include the main info about app-storage-behavior

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/app-storage#40]
@cdata @rictic would it be possible to either a) get tedium generating the docs for app-storage-behavior in the README or b) blacklist tedium from this repo and write out a readme that more accurately describes the contents of the repo?

**Comment by rictic** [comment]
Ok, reran tedium and now that the behavior has `@polymerBehavior` on it, it shows up in the README.

Now to teach tedium to put it at the top of the repo, and to improve the toplevel doc for AppStorageBehavior.
