### ISSUE TITLE
Error importing the app-indexeddb-mirror.html

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/app-storage#43]
Error when I import the `app-storage/app-indexeddb-mirror/app-indexeddb-mirror.html`.
Only import, even without instantiating the element.

![screen shot 2016-05-30 at 13 25 28](https://cloud.githubusercontent.com/assets/1007051/15648381/7ec821ba-266a-11e6-9028-7b772adf4a23.png)

All my code [is here](https://github.com/GDGSpain/gdg.es/blob/develop/src/pages/gdgspain-groups.html#L8).

**Comment by abdonrd** [comment]
The [common-worker.html error](https://github.com/PolymerElements/app-storage/blob/master/app-indexeddb-mirror/common-worker.html#L17-L19) is because the `document._currentScript` is `undefined`:

``` javascript
var BASE_URI = document._currentScript.ownerDocument.baseURI;
var WORKER_SCOPE_URL = Polymer.ResolveUrl.resolveUrl('common-worker-scope.js', BASE_URI);
```

( I has tried to hardcoded the `WORKER_SCOPE_URL` variable, and it works. )

**Comment by skeemer** [comment]
I've been running into this and wondered why something that seems better was removed. https://github.com/PolymerElements/app-storage/commit/cd26416060df7d801b7af10ceb86a41b96875dd8#commitcomment-17661405

**Comment by abdonrd** [comment]
Thanks for the reference, @skeemer!

**Comment by abdonrd** [comment]
I think we need to remove the underscore. From:

``` javascript
var BASE_URI = document._currentScript.ownerDocument.baseURI;
```

To: 

``` javascript
var BASE_URI = document.currentScript.ownerDocument.baseURI;
```

And the webcomponents.js make the polyfill.

**Comment by neckaros** [comment]
I had the same issue. polyfill use document._currentScript but for navigator that don't need polyfill var document._currentScript does not exist.

Using var BASE_URI = document.currentScript.ownerDocument.baseURI;
works like a charm on chrome :)

**Comment by Borjagodoy** [comment]
@cdata any news about this?

**Comment by abdonrd** [comment]
Any news @cdata? Right now we can't use the component without the polyfill :(

**Comment by jesusprubio** [comment]
Any news @cdata? :(

**Comment by dtruffaut** [comment]
Same problem here. 

How can we solve this ?

**Comment by abdonrd** [comment]
Yay! 😀

**Comment by TomK** [comment]
@cdata within the last few days this seems to have reappeared on `2.0-preview`.  Should #66 also be applied to that branch?
![image](https://cloud.githubusercontent.com/assets/299656/22834136/155caf8c-efac-11e6-892f-71119822f311.png)
