### ISSUE TITLE
Sintax error on Safari

### ISSUE THREAD

**Issue by JpOnline** [PolymerElements/app-storage#47]
Error using `app-indexeddb-mirror` on safari.

![captura de tela 2016-05-31 as 10 35 07](https://cloud.githubusercontent.com/assets/2047803/15676154/8b7ba646-271b-11e6-90d8-a4ad5974be4f.png)

![captura de tela 2016-05-31 as 10 31 22](https://cloud.githubusercontent.com/assets/2047803/15676167/95441c12-271b-11e6-8d4a-22b4b7926832.png)

**Comment by cdata** [comment]
Nice catch, thanks! I'll get a fix in for this..
