### ISSUE TITLE
Error to connect to IndexDB in Android device

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/app-storage#49]
### Description

With this simple code:

<img width="667" alt="screen shot 2016-05-31 at 17 31 36" src="https://cloud.githubusercontent.com/assets/1007051/15694704/6497e76c-27a0-11e6-8186-37c108280054.png">

In desktop everything works, but in Android device (remote debugging in Nexus 5X) I have this error to connect to IndexDB:

<img width="929" alt="screen shot 2016-05-31 at 17 15 20" src="https://cloud.githubusercontent.com/assets/1007051/15694675/281222b2-27a0-11e6-99ae-b300316a95e7.png">

**Comment by BorntraegerMarc** [comment]
I think the problem arises if you build the project with `polymer build`

**Comment by BorntraegerMarc** [comment]
Found the solution. I added:
```
    "bower_components/app-storage/app-indexeddb-mirror/app-indexeddb-mirror-worker.js",
    "bower_components/app-storage/app-indexeddb-mirror/common-worker-scope.js"
```

To `polymer.json`. From the polymer starter kit

**Comment by BorntraegerMarc** [comment]
However when I run the demo then my `persistedData` never takes the values from indexdb. I put in manually some values in there but `persistedData` is not updated. @abdonrd you ever had that issue?

**Comment by abdonrd** [comment]
I think is the same issue: https://github.com/Polymer/polymer-build/issues/22

**Comment by BorntraegerMarc** [comment]
@abdonrd but it worked for me with adding it to the polymer.json... and doesn't explain that `persistedData` does not updated, right?

**Comment by abdonrd** [comment]
When I tried this, didn't work: https://github.com/Polymer/polymer-build/issues/22#issuecomment-248537950

**Comment by BorntraegerMarc** [comment]
jep, saw that thanks @abdonrd :) but I was more asking about the general usage (because documentation is veeery limited for this element).
So `persistedData` actually never got updated. Also not if I served it over `polymer serve` alone. Did it ever work for you?

**Comment by abdonrd** [comment]
Yes, with `polymer serve` it works for me:

<img width="636" alt="screen shot 2017-04-04 at 12 36 14 pm" src="https://cloud.githubusercontent.com/assets/1007051/24652774/62871b98-1933-11e7-8b82-c52da92268da.png">

**Comment by BorntraegerMarc** [comment]
@abdonrd Could you help me out real quick? I only get the `persistedData` if the normal `data` (or `liveData`) has been set/updated:
![image](https://cloud.githubusercontent.com/assets/7549295/24653045/762c89e8-1934-11e7-89d6-9fdce8f43541.png)

I included it:
```
<app-indexeddb-mirror
                    id="appindexdb"
                    key="cats" log
                    data="{{liveData}}"
                    persisted-data="{{persistedData}}">
</app-indexeddb-mirror>
```

But I never set `liveData` to a value. It's `undefined`. I expect that the element would load `persistedData` automatically from the `mirrored_data` DB:
![image](https://cloud.githubusercontent.com/assets/7549295/24653135/d8b6eb3a-1934-11e7-87e9-d8fe6f2ab04b.png)

Is that not the case?

**Comment by abdonrd** [comment]
@BorntraegerMarc try to isolate the problem in a pastebin and I'll check it out.

**Comment by hyyan** [comment]
@abdonrd This issue is one year old and still no solution?

**Comment by abdonrd** [comment]
@hyyan I'm sorry, but I have not tried again about this.

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
