### ISSUE TITLE
having two different keys in app-localstorage-document

### ISSUE THREAD

**Issue by garcus** [PolymerElements/app-storage#51]
### Description
When using the app-localstorage-document element to store data on different keys the data of key1 is overwritten by data for key2 when key2 data is updated.

### Expected outcome
When data for key2 is updated it should only write to key2 data in localStorage. Not overwrite data of key1.

### Actual outcome
The data for key1 is overwritten

### Steps to reproduce
1. Create an app-localstorage-document element with key="key1" and bind data to something like {{dataone}}
2. Create another app-localstorage-document element with key="key2" and bind data to something like {{datatwo}}
3. Make a simple interaction from your app to change the data for key2 (datatwo)
4. dataone(key1) will now be overwritten with the contents of datatwo

### Browsers Affected
Only tried Chrome (Windows) so far

### Workaround
I made [this patch](https://github.com/garcus/app-storage/commit/cf69a4ec97c1694fe9f07f0ea6a781ebbb7ab7b6) to make it work but I'm not sure it's the right approach. My data for the different keys are updated as expected anyway.

**Comment by gitact** [comment]
I lost my last days on the same problem :-(

**Comment by cherukumilli** [comment]
@garcus 
Can you please submit a PR for this fix?

**Comment by eduardosada** [comment]
:(
This should be fixed asap.

**Comment by cherukumilli** [comment]
@garcus 

Looks like this issue can be closed as PR #52 has been merged into master and 0.9.5

**Comment by garcus** [comment]
Agree. Thanks!

**Comment by satyanath** [comment]
When is this going to be merged into 2.0 preview branch?
