### ISSUE TITLE
Persisted data becomes live data if online state changes

### ISSUE THREAD

**Issue by JaySunSyn** [PolymerElements/app-storage#54]
### Description

`app-indexeddb-mirror`
Persisted data gets unlinked when going online from an offline state, why?

`__updatePersistedData(client, key, session, online)`
### Expected outcome

Persisted data stays the same until live data gets updated.
### Actual outcome

Persisted data becomes live data when going online even though live data stays the same e.g. `undefined`
### Steps to reproduce

1. Load some data online (live=persisted)
2. Go offline & reload (live = undefined, persisted = persisted)
3. Go online (live = undefined, persisted = live)

**Comment by cdata** [comment]
Hi, thanks for reporting!

There is a good chance this is due to `undefined` being interpreted as a non-value, so the persisted data doesn't get unset.

@JaySunSyn can you provide an example dataset (persisted and live) that results in this problem?

**Comment by JaySunSyn** [comment]
Hi, thanks for answering @cdata !

I think its basically because of the observer is listening to online network status and updates persisted data if it changes. 

```
observers: [
          '__updatePersistedData(client, key, session, online)',
          '__updatePersistedData(data.*)',
        ],
```

Imo this could work:
```
observers: [
          '__updatePersistedData(client, key, session)',
          '__updatePersistedData(data.*)',
        ],
```

I guess there was a reason to observe the online status (?) and I might not get the reasoning behind it.
