### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by craftyc0der** [PolymerElements/app-storage#55]
I get the above error when I when I include the app-indexeddb-mirror tag in my element. It also fails to store any data. Any thoughts on the problem?

`Uncaught TypeError: Cannot read property 'ownerDocument' of undefined` 
` (anonymous function) @ common-worker.html:17` 
` (anonymous function) @ common-worker.html:102`

**Comment by craftyc0der** [comment]
If I include:
`<script src="../../bower_components/app-storage/app-indexeddb-mirror/app-indexeddb-mirror-worker.js">`
I still get the above error, but I also get some other encouraging things in my log:
`Opening `database..`
`app-indexeddb-mirror-worker.js:60` AppIndexedDBMirrorWorker started...
`app-indexeddb-mirror-worker.js:85` Database opened.`
My website does not render at all however when the above is included. There are no addition errors, just a white page.

**Comment by abdonrd** [comment]
The same as https://github.com/PolymerElements/app-storage/issues/43 and https://github.com/PolymerElements/app-storage/pull/45

**Comment by craftyc0der** [comment]
Sorry for the repeat.
