### ISSUE TITLE
app-indexeddb-mirror-worker.js and common-worker-scope.js not copied on build

### ISSUE THREAD

**Issue by deltaepsilon** [PolymerElements/app-storage#70]
### Description
```polymer build``` does not copy ```app-indexeddb-mirror-worker.js``` and ```common-worker-scope.js``` to the proper folders. This causes common-worker.html:46—``` return new SharedWorker(workerUrl);```—to fail silently. The symptom is that the console logs out ```App IndexedDB Client connecting..```, but the IndexedDB Client never connects.

### Expected outcome

If the two files are copied correctly, the new SharedWorker call succeeds and the IndexedDB Client connects as expected. This works fine in development.

### Actual outcome

Running ```polymer build && polymer serve build/unbundled``` will surface the problem, because the two *.js files are missing in the build. The client never connects.

### Temporary Solution

Add the two files to ```polymer.json``` in the ```includeDependencies``` array. This causes them to copy over correctly during the build process.

```
"includeDependencies": [
    "manifest.json",
    "bower_components/webcomponentsjs/webcomponents-lite.min.js",
    "bower_components/app-storage/app-indexeddb-mirror/app-indexeddb-mirror-worker.js",
    "bower_components/app-storage/app-indexeddb-mirror/common-worker-scope.js"
  ]
```

**Comment by abdonrd** [comment]
Probably related: https://github.com/Polymer/polymer-build/issues/22

**Comment by deltaepsilon** [comment]
Yep! That's it. I'll close this issue as a duplicate.
