### ISSUE TITLE
app-indexeddb-mirror cause app not responding

### ISSUE THREAD

**Issue by NaqashPixy** [PolymerElements/app-storage#95]
when i add app-indexeddb-mirror in my app and run app the page goes to "not responding"
few days back it was working fine 
i am using app-storage#2.0-preview

**Comment by e111077** [comment]
Hi, what browser is giving you this error. Does clearing page data do anything? Most recent changes have been to the sharedWorker

**Comment by NaqashPixy** [comment]
thanks dear issue resolved
it was due to webcomponent.js
